[project]
name = 'Peer-to-Peer-Ridesharing-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation-system_]
path = 'contracts/reputation-system_.clar'
clarity_version = 2
epoch = 2.5

[contracts.ride-management]
path = 'contracts/ride-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
